---
- name: install | Ensure dependencies are installed.
  ansible.builtin.package:
    name:
      - lsof
      - acl
      - sudo
    state: present

- name: install | Ensure service wrapper is installed for RHEL 9+.
  ansible.builtin.package:
    name:
      - initscripts-service
      - chkconfig
    state: present
  when:
    - ansible_service_mgr == 'systemd'
    - ansible_os_family == 'RedHat'
    - ansible_distribution_version.split(".")[0] >= '9'

- name: install | Ensure service wrapper is installed for RHEL 7 & 8.
  ansible.builtin.package:
    name:
      - initscripts
      - chkconfig
    state: present
  when:
    - ansible_service_mgr == 'systemd'
    - ansible_os_family == 'RedHat'
    - ansible_distribution_version.split(".")[0] <= '8'

- name: install | Ensure service wrapper is installed for Debian-based distributions.
  ansible.builtin.package:
    name: init-system-helpers
    state: present
  when:
    - ansible_service_mgr == 'systemd'
    - ansible_os_family == 'Debian'

# We add '-n' to Solr versions beyond 6.3.0 to prevent autostart on install.
- name: install | Run Solr installation script.
  ansible.builtin.command:
    "'>": ")) | ternary("
    creates: "{{"
    cmd: "{{ solr_workspace }}/{{ solr_filename }}/bin/install_solr_service.sh {{ solr_workspace }}/{{ solr_filename }}.tgz -i {{ solr_install_dir }} -d {{ solr_home
      }} -u {{ solr_user }} -s {{ solr_service_name }} -p {{ solr_port }} {{ (solr_version is version('6.3.0', -n','') }} {{ (solr_version is version('5.4.0', -f','')
      }} solr_install_path }}/bin/solr"
  register: solr_install_script_result

# Workaround for bug https://github.com/ansible/ansible-modules-core/issues/915.
- name: install | Ensure solr is stopped (RHEL 7+ workaround).
  command: service {{ solr_service_name }} stop
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_version.split(".")[0] >= '7'
    - solr_install_script_result.changed
  failed_when: false
  tags: ["skip_ansible_lint"]

- name: install | Run systemd daemon_reload (RHEL 7+ workaround).
  systemd:
    name: solr
    daemon_reload: true
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_version.split(".")[0] >= '7'
    - solr_install_script_result.changed
  tags: ["skip_ansible_lint"]
